from __future__ import annotations

from .exceptions import SchemaDriftError
from .lake import LakeDatabase
from .postgres import PostgresConnection
from .source import SourceDatabase
from .util import stable_json, utc_now_iso
from .warehouse import WarehouseDatabase

SCHEMA = "control"


class PipelineControl:
    def __init__(self, conn: PostgresConnection):
        self.conn = conn

    def close(self) -> None:
        return

    def initialize(self) -> None:
        with self.conn.transaction():
            self.conn.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")
            self.conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA}.pipeline_state (
                    id INTEGER PRIMARY KEY CHECK (id = 1),
                    last_change_id BIGINT NOT NULL,
                    source_schema_hash TEXT NOT NULL,
                    last_success_at TIMESTAMPTZ,
                    last_warning TEXT,
                    status TEXT NOT NULL
                )
                """
            )
            self.conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA}.schema_contracts (
                    contract_name TEXT PRIMARY KEY,
                    contract_json JSONB NOT NULL,
                    schema_hash TEXT NOT NULL,
                    captured_at TIMESTAMPTZ NOT NULL
                )
                """
            )
            self.conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA}.drift_alerts (
                    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    detected_at TIMESTAMPTZ NOT NULL,
                    baseline_hash TEXT NOT NULL,
                    current_hash TEXT NOT NULL,
                    details_json JSONB NOT NULL,
                    severity TEXT NOT NULL,
                    status TEXT NOT NULL
                )
                """
            )
            if int(self.conn.scalar(f"SELECT COUNT(*) FROM {SCHEMA}.pipeline_state WHERE id = 1", default=0)) == 0:
                self.conn.execute(f"INSERT INTO {SCHEMA}.pipeline_state(id, last_change_id, source_schema_hash, last_success_at, last_warning, status) VALUES (1, 0, '', NULL, NULL, 'idle')")

    def state(self) -> dict[str, object]:
        row = self.conn.query(f"SELECT * FROM {SCHEMA}.pipeline_state WHERE id = 1").fetchone()
        return row or {}

    def update_state(self, *, last_change_id: int | None = None, source_schema_hash: str | None = None, last_success_at: str | None = None, last_warning: str | None = None, status: str | None = None) -> None:
        current = self.state()
        self.conn.execute(
            f"""
            UPDATE {SCHEMA}.pipeline_state
            SET last_change_id = ?, source_schema_hash = ?, last_success_at = ?, last_warning = ?, status = ?
            WHERE id = 1
            """,
            (
                current.get("last_change_id") if last_change_id is None else last_change_id,
                current.get("source_schema_hash") if source_schema_hash is None else source_schema_hash,
                current.get("last_success_at") if last_success_at is None else last_success_at,
                current.get("last_warning") if last_warning is None else last_warning,
                current.get("status") if status is None else status,
            ),
        )

    def record_contract(self, contract_name: str, contract_json: str, schema_hash: str) -> None:
        self.conn.execute(
            f"""
            INSERT INTO {SCHEMA}.schema_contracts(contract_name, contract_json, schema_hash, captured_at)
            VALUES (?, ?::jsonb, ?, ?)
            ON CONFLICT (contract_name)
            DO UPDATE SET contract_json = EXCLUDED.contract_json, schema_hash = EXCLUDED.schema_hash, captured_at = EXCLUDED.captured_at
            """,
            (contract_name, contract_json, schema_hash, utc_now_iso()),
        )

    def alert_drift(self, baseline_hash: str, current_hash: str, details: dict[str, object]) -> None:
        self.conn.execute(
            f"""
            INSERT INTO {SCHEMA}.drift_alerts(detected_at, baseline_hash, current_hash, details_json, severity, status)
            VALUES (?, ?, ?, ?::jsonb, 'critical', 'open')
            """,
            (utc_now_iso(), baseline_hash, current_hash, stable_json(details)),
        )
        self.conn.execute(
            f"UPDATE {SCHEMA}.pipeline_state SET last_warning = ?, status = 'blocked' WHERE id = 1",
            (stable_json(details),),
        )


class CdcPipeline:
    def __init__(self, source: SourceDatabase, lake: LakeDatabase, warehouse: WarehouseDatabase, control: PipelineControl):
        self.source = source
        self.lake = lake
        self.warehouse = warehouse
        self.control = control

    def bootstrap_contract(self) -> str:
        schema_hash = self.source.schema_fingerprint()
        contract = self.source.schema_contract()
        contract_json = stable_json(
            {
                "table_name": contract.table_name,
                "columns": [
                    {
                        "table_name": c.table_name,
                        "column_name": c.column_name,
                        "data_type": c.data_type,
                        "notnull": c.notnull,
                        "is_pk": c.is_pk,
                        "default_value": c.default_value,
                        "ordinal": c.ordinal,
                    }
                    for c in contract.columns
                ],
                "foreign_keys": list(contract.foreign_keys),
                "indexes": list(contract.indexes),
            }
        )
        self.control.record_contract("source_contract", contract_json, schema_hash)
        self.control.update_state(source_schema_hash=schema_hash, status="ready")
        return schema_hash

    def detect_schema_drift(self) -> None:
        current_hash = self.source.schema_fingerprint()
        state = self.control.state()
        baseline_hash = state.get("source_schema_hash", "")
        if not baseline_hash:
            self.bootstrap_contract()
            return
        if current_hash != baseline_hash:
            details = {"message": "source schema changed; ingestion halted until contract review", "baseline_hash": baseline_hash, "current_hash": current_hash}
            self.control.alert_drift(baseline_hash, current_hash, details)
            raise SchemaDriftError(details["message"])

    def run_once(self) -> int:
        self.detect_schema_drift()
        state = self.control.state()
        last_change_id = int(state.get("last_change_id", 0))
        changes = self.source.fetch_changes_since(last_change_id)
        if not changes:
            self.control.update_state(status="idle", last_warning=None)
            return 0
        for change in changes:
            self.lake.append(change)
            self.warehouse.apply_change(change)
            self.control.update_state(last_change_id=change.change_id, last_success_at=utc_now_iso(), status="running")
        self.control.update_state(status="idle")
        return len(changes)

    def replay_from_beginning(self) -> int:
        self.control.update_state(last_change_id=0, status="running")
        return self.run_once()

