from __future__ import annotations

import json
from collections.abc import Iterable
from decimal import Decimal
from typing import Any

from .exceptions import ValidationError
from .models import ChangeEvent, SchemaColumn, TableContract
from .postgres import PostgresConnection
from .util import sha256_text, stable_json, utc_now_iso


SCHEMA = "source"

ALLOWED_CUSTOMER_STATUSES = {"active", "suspended", "closed"}
ALLOWED_PRODUCT_STATUSES = {"active", "discontinued"}
ALLOWED_ORDER_STATUSES = {"draft", "placed", "paid", "shipped", "completed", "cancelled", "refunded"}
ALLOWED_PAYMENT_STATUSES = {"pending", "authorized", "captured", "failed", "refunded"}
ALLOWED_ATTEMPT_STATUSES = {"started", "succeeded", "failed"}
ALLOWED_PAYMENT_METHODS = {"card", "bank_transfer", "wallet"}
ALLOWED_ADDRESS_TYPES = {"billing", "shipping"}


def _f(value: Any) -> float:
    return float(value) if value is not None else 0.0


def _i(value: Any) -> int:
    return int(value) if value is not None else 0


class SourceDatabase:
    def __init__(self, conn: PostgresConnection):
        self.conn = conn

    def close(self) -> None:
        return

    @staticmethod
    def tracked_tables() -> tuple[str, ...]:
        return ("customers", "customer_addresses", "products", "orders", "order_items", "payments", "payment_attempts")

    def initialize(self) -> None:
        with self.conn.transaction():
            self.conn.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")
            self.conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA}.customers (
                    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    external_customer_ref TEXT NOT NULL UNIQUE,
                    email TEXT NOT NULL UNIQUE,
                    full_name TEXT NOT NULL,
                    phone TEXT,
                    customer_status TEXT NOT NULL CHECK (customer_status IN ('active','suspended','closed')),
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL
                )
                """
            )
            self.conn.execute(f"CREATE INDEX IF NOT EXISTS idx_customers_status ON {SCHEMA}.customers(customer_status)")
            self.conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA}.customer_addresses (
                    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id BIGINT NOT NULL REFERENCES {SCHEMA}.customers(customer_id) ON DELETE CASCADE ON UPDATE CASCADE,
                    address_type TEXT NOT NULL CHECK (address_type IN ('billing','shipping')),
                    line1 TEXT NOT NULL,
                    line2 TEXT,
                    city TEXT NOT NULL,
                    state TEXT NOT NULL,
                    postal_code TEXT NOT NULL,
                    country_code TEXT NOT NULL,
                    is_default INTEGER NOT NULL CHECK (is_default IN (0,1)),
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL,
                    UNIQUE(customer_id, address_type, line1, postal_code)
                )
                """
            )
            self.conn.execute(f"CREATE INDEX IF NOT EXISTS idx_customer_addresses_customer ON {SCHEMA}.customer_addresses(customer_id, is_default)")
            self.conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA}.products (
                    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sku TEXT NOT NULL UNIQUE,
                    product_name TEXT NOT NULL,
                    category TEXT NOT NULL,
                    unit_price NUMERIC NOT NULL CHECK (unit_price >= 0),
                    product_status TEXT NOT NULL CHECK (product_status IN ('active','discontinued')),
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL
                )
                """
            )
            self.conn.execute(f"CREATE INDEX IF NOT EXISTS idx_products_status ON {SCHEMA}.products(product_status)")
            self.conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA}.orders (
                    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id BIGINT NOT NULL REFERENCES {SCHEMA}.customers(customer_id) ON DELETE RESTRICT ON UPDATE CASCADE,
                    order_number TEXT NOT NULL UNIQUE,
                    order_status TEXT NOT NULL CHECK (order_status IN ('draft','placed','paid','shipped','completed','cancelled','refunded')),
                    currency_code TEXT NOT NULL CHECK (length(currency_code) = 3),
                    subtotal NUMERIC NOT NULL CHECK (subtotal >= 0),
                    tax_amount NUMERIC NOT NULL CHECK (tax_amount >= 0),
                    shipping_amount NUMERIC NOT NULL CHECK (shipping_amount >= 0),
                    total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
                    placed_at TIMESTAMPTZ NOT NULL,
                    cancelled_at TIMESTAMPTZ,
                    billing_address_id BIGINT REFERENCES {SCHEMA}.customer_addresses(address_id) ON DELETE SET NULL ON UPDATE CASCADE,
                    shipping_address_id BIGINT REFERENCES {SCHEMA}.customer_addresses(address_id) ON DELETE SET NULL ON UPDATE CASCADE,
                    notes TEXT,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL
                )
                """
            )
            self.conn.execute(f"CREATE INDEX IF NOT EXISTS idx_orders_customer_status ON {SCHEMA}.orders(customer_id, order_status, placed_at)")
            self.conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA}.order_items (
                    order_id BIGINT NOT NULL REFERENCES {SCHEMA}.orders(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
                    line_number INTEGER NOT NULL,
                    product_id BIGINT NOT NULL REFERENCES {SCHEMA}.products(product_id) ON DELETE RESTRICT ON UPDATE CASCADE,
                    quantity INTEGER NOT NULL CHECK (quantity > 0),
                    unit_price NUMERIC NOT NULL CHECK (unit_price >= 0),
                    discount_amount NUMERIC NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
                    line_total NUMERIC NOT NULL CHECK (line_total >= 0),
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL,
                    PRIMARY KEY (order_id, line_number)
                )
                """
            )
            self.conn.execute(f"CREATE INDEX IF NOT EXISTS idx_order_items_product ON {SCHEMA}.order_items(product_id)")
            self.conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA}.payments (
                    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_id BIGINT NOT NULL REFERENCES {SCHEMA}.orders(order_id) ON DELETE RESTRICT ON UPDATE CASCADE,
                    payment_method TEXT NOT NULL CHECK (payment_method IN ('card','bank_transfer','wallet')),
                    payment_status TEXT NOT NULL CHECK (payment_status IN ('pending','authorized','captured','failed','refunded')),
                    amount NUMERIC NOT NULL CHECK (amount > 0),
                    provider_reference TEXT UNIQUE,
                    authorized_at TIMESTAMPTZ,
                    captured_at TIMESTAMPTZ,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL
                )
                """
            )
            self.conn.execute(f"CREATE INDEX IF NOT EXISTS idx_payments_order_status ON {SCHEMA}.payments(order_id, payment_status)")
            self.conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA}.payment_attempts (
                    payment_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    payment_id BIGINT NOT NULL REFERENCES {SCHEMA}.payments(payment_id) ON DELETE CASCADE ON UPDATE CASCADE,
                    attempt_no INTEGER NOT NULL CHECK (attempt_no > 0),
                    attempt_status TEXT NOT NULL CHECK (attempt_status IN ('started','succeeded','failed')),
                    decline_code TEXT,
                    gateway_latency_ms INTEGER CHECK (gateway_latency_ms IS NULL OR gateway_latency_ms >= 0),
                    attempted_at TIMESTAMPTZ NOT NULL,
                    request_id TEXT NOT NULL UNIQUE,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL,
                    UNIQUE(payment_id, attempt_no)
                )
                """
            )
            self.conn.execute(f"CREATE INDEX IF NOT EXISTS idx_payment_attempts_payment ON {SCHEMA}.payment_attempts(payment_id, attempted_at)")
            self.conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA}.cdc_log (
                    change_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    table_name TEXT NOT NULL,
                    op TEXT NOT NULL CHECK (op IN ('I','U','D')),
                    entity_key JSONB NOT NULL,
                    source_commit_ts TIMESTAMPTZ NOT NULL,
                    source_txn_id TEXT NOT NULL,
                    before_json JSONB,
                    after_json JSONB,
                    source_schema_hash TEXT NOT NULL
                )
                """
            )
            self.conn.execute(f"CREATE INDEX IF NOT EXISTS idx_cdc_log_change_id ON {SCHEMA}.cdc_log(change_id)")
            self.conn.execute(f"CREATE INDEX IF NOT EXISTS idx_cdc_log_table_change_id ON {SCHEMA}.cdc_log(table_name, change_id)")

    def _raw_row(self, table: str, where_sql: str, params: Iterable[Any]) -> dict[str, Any] | None:
        result = self.conn.query(f"SELECT * FROM {SCHEMA}.{table} WHERE {where_sql} LIMIT 1", tuple(params))
        return result.fetchone()

    def _normalize(self, table: str, row: dict[str, Any] | None) -> dict[str, Any] | None:
        if row is None:
            return None
        converted = dict(row)
        for key in list(converted):
            if key in {"customer_id", "address_id", "product_id", "order_id", "payment_id", "payment_attempt_id", "line_number", "quantity", "attempt_no", "gateway_latency_ms"}:
                converted[key] = None if converted[key] is None else int(converted[key])
            if key in {"unit_price", "discount_amount", "line_total", "subtotal", "tax_amount", "shipping_amount", "total_amount", "amount"}:
                converted[key] = None if converted[key] is None else float(converted[key])
            if key in {"is_default"}:
                converted[key] = int(converted[key])
        return converted

    def _row(self, table: str, where_sql: str, params: Iterable[Any]) -> dict[str, Any] | None:
        return self._normalize(table, self._raw_row(table, where_sql, params))

    def schema_contract(self) -> TableContract:
        columns: list[SchemaColumn] = []
        foreign_keys: list[tuple[str, str, str]] = []
        indexes: list[str] = []
        table_names = ", ".join(quote for quote in [f"'{t}'" for t in self.tracked_tables()])
        for row in self.conn.query(
            f"""
            SELECT table_name, column_name, data_type, is_nullable, column_default, ordinal_position
            FROM information_schema.columns
            WHERE table_schema = '{SCHEMA}'
              AND table_name IN ({table_names})
            ORDER BY table_name, ordinal_position
            """
        ).fetchall():
            columns.append(
                SchemaColumn(
                    table_name=row["table_name"],
                    column_name=row["column_name"],
                    data_type=row["data_type"],
                    notnull=row["is_nullable"] == "NO",
                    is_pk=False,
                    default_value=row["column_default"],
                    ordinal=int(row["ordinal_position"]),
                )
            )
        pk_rows = self.conn.query(
            f"""
            SELECT kcu.table_name, kcu.column_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            WHERE tc.table_schema = '{SCHEMA}' AND tc.constraint_type = 'PRIMARY KEY'
            ORDER BY kcu.table_name, kcu.ordinal_position
            """
        ).fetchall()
        pk_map = {(row["table_name"], row["column_name"]) for row in pk_rows}
        columns = [
            SchemaColumn(
                table_name=c.table_name,
                column_name=c.column_name,
                data_type=c.data_type,
                notnull=c.notnull,
                is_pk=(c.table_name, c.column_name) in pk_map,
                default_value=c.default_value,
                ordinal=c.ordinal,
            )
            for c in columns
        ]
        for row in self.conn.query(
            f"""
            SELECT tc.table_name, kcu.column_name, ccu.table_name AS foreign_table, ccu.column_name AS foreign_column
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            JOIN information_schema.constraint_column_usage ccu
              ON tc.constraint_name = ccu.constraint_name
             AND tc.table_schema = ccu.table_schema
            WHERE tc.table_schema = '{SCHEMA}' AND tc.constraint_type = 'FOREIGN KEY'
            ORDER BY tc.table_name, kcu.ordinal_position
            """
        ).fetchall():
            foreign_keys.append((row["table_name"], row["column_name"], f"{row['foreign_table']}.{row['foreign_column']}"))
        for row in self.conn.query(
            f"""
            SELECT indexname, indexdef
            FROM pg_indexes
            WHERE schemaname = '{SCHEMA}'
            ORDER BY indexname
            """
        ).fetchall():
            indexes.append(f"{row['indexname']}:{row['indexdef']}")
        return TableContract(table_name=f"{SCHEMA}.contract", columns=tuple(columns), foreign_keys=tuple(foreign_keys), indexes=tuple(indexes))

    def schema_fingerprint(self) -> str:
        contract = self.schema_contract()
        payload = {
            "columns": [
                {
                    "table_name": c.table_name,
                    "column_name": c.column_name,
                    "data_type": c.data_type,
                    "notnull": c.notnull,
                    "is_pk": c.is_pk,
                    "default_value": c.default_value,
                    "ordinal": c.ordinal,
                }
                for c in contract.columns
            ],
            "foreign_keys": list(contract.foreign_keys),
            "indexes": sorted(contract.indexes),
        }
        return sha256_text(stable_json(payload))

    def _record_change(self, *, table_name: str, op: str, entity_key: dict[str, Any], before: dict[str, Any] | None, after: dict[str, Any] | None) -> int:
        commit_ts = utc_now_iso()
        txn_id = f"{table_name}:{op}:{commit_ts}:{stable_json(entity_key)}"
        row = self.conn.query(
            f"""
            INSERT INTO {SCHEMA}.cdc_log (
                table_name, op, entity_key, source_commit_ts, source_txn_id, before_json, after_json, source_schema_hash
            ) VALUES (?, ?, ?::jsonb, ?, ?, ?::jsonb, ?::jsonb, ?)
            RETURNING change_id
            """,
            (
                table_name,
                op,
                stable_json(entity_key),
                commit_ts,
                txn_id,
                None if before is None else stable_json(before),
                None if after is None else stable_json(after),
                self.schema_fingerprint(),
            ),
        ).fetchone()
        return int(row["change_id"])

    def fetch_changes_since(self, change_id: int) -> list[ChangeEvent]:
        def _normalize_json(value: Any) -> dict[str, Any] | None:
            if value is None:
                return None
            if isinstance(value, dict):
                return value
            if isinstance(value, str):
                return json.loads(value)
            raise TypeError(f"unsupported JSON value type: {type(value).__name__}")

        rows = self.conn.query(
            f"""
            SELECT change_id, table_name, op, entity_key, source_commit_ts, source_txn_id, before_json, after_json, source_schema_hash
            FROM {SCHEMA}.cdc_log
            WHERE change_id > ?
            ORDER BY change_id
            """,
            (change_id,),
        ).fetchall()
        events: list[ChangeEvent] = []
        for row in rows:
            events.append(
                ChangeEvent(
                    change_id=int(row["change_id"]),
                    table_name=row["table_name"],
                    op=row["op"],
                    entity_key=_normalize_json(row["entity_key"]) or {},
                    source_commit_ts=row["source_commit_ts"],
                    source_txn_id=row["source_txn_id"],
                    before=_normalize_json(row["before_json"]),
                    after=_normalize_json(row["after_json"]),
                    source_schema_hash=row["source_schema_hash"],
                )
            )
        return events

    def seed_demo_data(self) -> None:
        if self.conn.scalar(f"SELECT COUNT(*) FROM {SCHEMA}.customers", default=0) > 0:
            return
        now = utc_now_iso()
        with self.conn.transaction():
            customer_1 = self.insert_customer(external_customer_ref="CUST-1001", email="maya.rao@example.com", full_name="Maya Rao", phone="+91-99999-10001", customer_status="active", created_at=now)
            customer_2 = self.insert_customer(external_customer_ref="CUST-1002", email="arjun.singh@example.com", full_name="Arjun Singh", phone=None, customer_status="active", created_at=now)
            billing = self.insert_address(customer_id=customer_1, address_type="billing", line1="12 MG Road", line2=None, city="Bengaluru", state="KA", postal_code="560001", country_code="IN", is_default=True, created_at=now)
            shipping = self.insert_address(customer_id=customer_1, address_type="shipping", line1="12 MG Road", line2="Apt 4B", city="Bengaluru", state="KA", postal_code="560001", country_code="IN", is_default=True, created_at=now)
            products = [
                self.insert_product("SKU-100", "Noise Cancelling Headphones", "electronics", 12999.00, "active", now),
                self.insert_product("SKU-200", "Laptop Stand", "accessories", 2199.00, "active", now),
                self.insert_product("SKU-300", "USB-C Hub", "accessories", 2499.00, "active", now),
                self.insert_product("SKU-400", "Mechanical Keyboard", "electronics", 6999.00, "active", now),
            ]
            order_id = self.insert_order(customer_id=customer_1, order_number="ORD-2026-0001", order_status="draft", currency_code="INR", subtotal=0, tax_amount=0, shipping_amount=0, total_amount=0, placed_at=now, cancelled_at=None, billing_address_id=billing, shipping_address_id=shipping, notes="Initial seeding order", created_at=now)
            self.insert_order_item(order_id, 1, products[0], 1, 12999.00, 0, now)
            self.insert_order_item(order_id, 2, products[1], 1, 2199.00, 0, now)
            self.finalize_order(order_id, tax_amount=600.00, shipping_amount=99.00, status="placed")
            payment_id = self.insert_payment(order_id=order_id, payment_method="card", payment_status="authorized", amount=15997.00, provider_reference="AUTH-XYZ-1001", authorized_at=now, captured_at=None, created_at=now)
            self.insert_payment_attempt(payment_id=payment_id, attempt_no=1, attempt_status="succeeded", decline_code=None, gateway_latency_ms=350, attempted_at=now, request_id="REQ-1", created_at=now)
            second_order = self.insert_order(customer_id=customer_2, order_number="ORD-2026-0002", order_status="draft", currency_code="INR", subtotal=0, tax_amount=0, shipping_amount=0, total_amount=0, placed_at=now, cancelled_at=None, billing_address_id=None, shipping_address_id=None, notes=None, created_at=now)
            self.insert_order_item(second_order, 1, products[2], 2, 2499.00, 0, now)
            self.finalize_order(second_order, tax_amount=225.00, shipping_amount=49.00, status="placed")
            self.insert_payment(order_id=second_order, payment_method="wallet", payment_status="pending", amount=5272.00, provider_reference="WALLET-2001", authorized_at=None, captured_at=None, created_at=now)

    def introduce_breaking_schema_change(self) -> None:
        with self.conn.transaction():
            self.conn.execute(f"ALTER TABLE {SCHEMA}.products RENAME COLUMN unit_price TO price_amount")

    def insert_customer(self, *, external_customer_ref: str, email: str, full_name: str, phone: str | None, customer_status: str, created_at: str | None = None) -> int:
        if customer_status not in ALLOWED_CUSTOMER_STATUSES:
            raise ValidationError(f"invalid customer_status: {customer_status}")
        now = created_at or utc_now_iso()
        row = self.conn.query(
            f"""
            INSERT INTO {SCHEMA}.customers (external_customer_ref, email, full_name, phone, customer_status, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            RETURNING customer_id
            """,
            (external_customer_ref, email, full_name, phone, customer_status, now, now),
        ).fetchone()
        customer_id = int(row["customer_id"])
        after = self._row("customers", "customer_id = ?", [customer_id])
        self._record_change(table_name="customers", op="I", entity_key={"customer_id": customer_id}, before=None, after=after)
        return customer_id

    def insert_address(self, *, customer_id: int, address_type: str, line1: str, line2: str | None, city: str, state: str, postal_code: str, country_code: str, is_default: bool, created_at: str | None = None) -> int:
        if address_type not in ALLOWED_ADDRESS_TYPES:
            raise ValidationError(f"invalid address_type: {address_type}")
        now = created_at or utc_now_iso()
        row = self.conn.query(
            f"""
            INSERT INTO {SCHEMA}.customer_addresses (customer_id, address_type, line1, line2, city, state, postal_code, country_code, is_default, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING address_id
            """,
            (customer_id, address_type, line1, line2, city, state, postal_code, country_code, 1 if is_default else 0, now, now),
        ).fetchone()
        address_id = int(row["address_id"])
        after = self._row("customer_addresses", "address_id = ?", [address_id])
        self._record_change(table_name="customer_addresses", op="I", entity_key={"address_id": address_id}, before=None, after=after)
        return address_id

    def insert_product(self, sku: str, product_name: str, category: str, unit_price: float, product_status: str, created_at: str | None = None) -> int:
        if product_status not in ALLOWED_PRODUCT_STATUSES:
            raise ValidationError(f"invalid product_status: {product_status}")
        if unit_price < 0:
            raise ValidationError("unit_price cannot be negative")
        now = created_at or utc_now_iso()
        row = self.conn.query(
            f"""
            INSERT INTO {SCHEMA}.products (sku, product_name, category, unit_price, product_status, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            RETURNING product_id
            """,
            (sku, product_name, category, unit_price, product_status, now, now),
        ).fetchone()
        product_id = int(row["product_id"])
        after = self._row("products", "product_id = ?", [product_id])
        self._record_change(table_name="products", op="I", entity_key={"product_id": product_id}, before=None, after=after)
        return product_id

    def insert_order(self, *, customer_id: int, order_number: str, order_status: str, currency_code: str, subtotal: float, tax_amount: float, shipping_amount: float, total_amount: float, placed_at: str, cancelled_at: str | None, billing_address_id: int | None, shipping_address_id: int | None, notes: str | None, created_at: str | None = None) -> int:
        if order_status not in ALLOWED_ORDER_STATUSES:
            raise ValidationError(f"invalid order_status: {order_status}")
        if len(currency_code) != 3:
            raise ValidationError("currency_code must be ISO-4217-like")
        if min(subtotal, tax_amount, shipping_amount, total_amount) < 0:
            raise ValidationError("order monetary fields cannot be negative")
        now = created_at or utc_now_iso()
        row = self.conn.query(
            f"""
            INSERT INTO {SCHEMA}.orders (
                customer_id, order_number, order_status, currency_code, subtotal, tax_amount, shipping_amount,
                total_amount, placed_at, cancelled_at, billing_address_id, shipping_address_id, notes, created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING order_id
            """,
            (customer_id, order_number, order_status, currency_code, subtotal, tax_amount, shipping_amount, total_amount, placed_at, cancelled_at, billing_address_id, shipping_address_id, notes, now, now),
        ).fetchone()
        order_id = int(row["order_id"])
        after = self._row("orders", "order_id = ?", [order_id])
        self._record_change(table_name="orders", op="I", entity_key={"order_id": order_id}, before=None, after=after)
        return order_id

    def insert_order_item(self, order_id: int, line_number: int, product_id: int, quantity: int, unit_price: float, discount_amount: float, created_at: str | None = None) -> None:
        if quantity <= 0:
            raise ValidationError("quantity must be positive")
        if unit_price < 0 or discount_amount < 0:
            raise ValidationError("prices cannot be negative")
        now = created_at or utc_now_iso()
        line_total = round(quantity * unit_price - discount_amount, 2)
        if line_total < 0:
            raise ValidationError("line_total cannot be negative")
        self.conn.execute(
            f"""
            INSERT INTO {SCHEMA}.order_items (
                order_id, line_number, product_id, quantity, unit_price, discount_amount, line_total, created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (order_id, line_number, product_id, quantity, unit_price, discount_amount, line_total, now, now),
        )
        after = self._row("order_items", "order_id = ? AND line_number = ?", [order_id, line_number])
        self._record_change(table_name="order_items", op="I", entity_key={"order_id": order_id, "line_number": line_number}, before=None, after=after)

    def finalize_order(self, order_id: int, *, tax_amount: float, shipping_amount: float, status: str) -> None:
        if status not in {"placed", "paid"}:
            raise ValidationError("finalized orders must move to placed or paid")
        before = self._row("orders", "order_id = ?", [order_id])
        if before is None:
            raise ValidationError(f"order_id {order_id} not found")
        allowed = {"draft": {"placed", "cancelled"}, "placed": {"paid", "cancelled"}, "paid": {"shipped", "refunded"}, "shipped": {"completed", "refunded"}, "completed": set(), "cancelled": set(), "refunded": set()}
        if status not in allowed[before["order_status"]]:
            raise ValidationError(f"invalid order transition {before['order_status']} -> {status}")
        items_total = self.conn.scalar(f"SELECT COALESCE(SUM(line_total), 0) FROM {SCHEMA}.order_items WHERE order_id = ?", (order_id,), default=0)
        total_amount = round(float(items_total) + tax_amount + shipping_amount, 2)
        now = utc_now_iso()
        cancelled_at = now if status == "cancelled" else before["cancelled_at"]
        self.conn.execute(
            f"""
            UPDATE {SCHEMA}.orders
            SET order_status = ?, subtotal = ?, tax_amount = ?, shipping_amount = ?, total_amount = ?, cancelled_at = ?, updated_at = ?
            WHERE order_id = ?
            """,
            (status, round(float(items_total), 2), round(tax_amount, 2), round(shipping_amount, 2), total_amount, cancelled_at, now, order_id),
        )
        after = self._row("orders", "order_id = ?", [order_id])
        self._record_change(table_name="orders", op="U", entity_key={"order_id": order_id}, before=before, after=after)

    def update_customer_status(self, customer_id: int, customer_status: str) -> None:
        if customer_status not in ALLOWED_CUSTOMER_STATUSES:
            raise ValidationError(f"invalid customer_status: {customer_status}")
        before = self._row("customers", "customer_id = ?", [customer_id])
        if before is None:
            raise ValidationError(f"customer_id {customer_id} not found")
        now = utc_now_iso()
        self.conn.execute(
            f"UPDATE {SCHEMA}.customers SET customer_status = ?, updated_at = ? WHERE customer_id = ?",
            (customer_status, now, customer_id),
        )
        after = self._row("customers", "customer_id = ?", [customer_id])
        self._record_change(table_name="customers", op="U", entity_key={"customer_id": customer_id}, before=before, after=after)

    def insert_payment(self, *, order_id: int, payment_method: str, payment_status: str, amount: float, provider_reference: str | None, authorized_at: str | None, captured_at: str | None, created_at: str | None = None) -> int:
        if payment_method not in ALLOWED_PAYMENT_METHODS:
            raise ValidationError(f"invalid payment_method: {payment_method}")
        if payment_status not in ALLOWED_PAYMENT_STATUSES:
            raise ValidationError(f"invalid payment_status: {payment_status}")
        if amount <= 0:
            raise ValidationError("payment amount must be positive")
        now = created_at or utc_now_iso()
        row = self.conn.query(
            f"""
            INSERT INTO {SCHEMA}.payments (order_id, payment_method, payment_status, amount, provider_reference, authorized_at, captured_at, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING payment_id
            """,
            (order_id, payment_method, payment_status, amount, provider_reference, authorized_at, captured_at, now, now),
        ).fetchone()
        payment_id = int(row["payment_id"])
        after = self._row("payments", "payment_id = ?", [payment_id])
        self._record_change(table_name="payments", op="I", entity_key={"payment_id": payment_id}, before=None, after=after)
        return payment_id

    def insert_payment_attempt(self, *, payment_id: int, attempt_no: int, attempt_status: str, decline_code: str | None, gateway_latency_ms: int | None, attempted_at: str, request_id: str, created_at: str | None = None) -> int:
        if attempt_status not in ALLOWED_ATTEMPT_STATUSES:
            raise ValidationError(f"invalid attempt_status: {attempt_status}")
        if attempt_no <= 0:
            raise ValidationError("attempt_no must be positive")
        if gateway_latency_ms is not None and gateway_latency_ms < 0:
            raise ValidationError("gateway_latency_ms must be non-negative")
        now = created_at or utc_now_iso()
        row = self.conn.query(
            f"""
            INSERT INTO {SCHEMA}.payment_attempts (payment_id, attempt_no, attempt_status, decline_code, gateway_latency_ms, attempted_at, request_id, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING payment_attempt_id
            """,
            (payment_id, attempt_no, attempt_status, decline_code, gateway_latency_ms, attempted_at, request_id, now, now),
        ).fetchone()
        payment_attempt_id = int(row["payment_attempt_id"])
        after = self._row("payment_attempts", "payment_attempt_id = ?", [payment_attempt_id])
        self._record_change(table_name="payment_attempts", op="I", entity_key={"payment_attempt_id": payment_attempt_id}, before=None, after=after)
        return payment_attempt_id

    def update_payment_status(self, payment_id: int, payment_status: str, *, captured_at: str | None = None) -> None:
        if payment_status not in ALLOWED_PAYMENT_STATUSES:
            raise ValidationError(f"invalid payment_status: {payment_status}")
        before = self._row("payments", "payment_id = ?", [payment_id])
        if before is None:
            raise ValidationError(f"payment_id {payment_id} not found")
        now = utc_now_iso()
        self.conn.execute(
            f"UPDATE {SCHEMA}.payments SET payment_status = ?, captured_at = COALESCE(?, captured_at), updated_at = ? WHERE payment_id = ?",
            (payment_status, captured_at, now, payment_id),
        )
        after = self._row("payments", "payment_id = ?", [payment_id])
        self._record_change(table_name="payments", op="U", entity_key={"payment_id": payment_id}, before=before, after=after)

    def delete_order_item(self, order_id: int, line_number: int) -> None:
        before = self._row("order_items", "order_id = ? AND line_number = ?", [order_id, line_number])
        if before is None:
            raise ValidationError(f"order_item {order_id}/{line_number} not found")
        self.conn.execute(f"DELETE FROM {SCHEMA}.order_items WHERE order_id = ? AND line_number = ?", (order_id, line_number))
        self._record_change(table_name="order_items", op="D", entity_key={"order_id": order_id, "line_number": line_number}, before=before, after=None)

    def counts(self) -> dict[str, int]:
        return {table: int(self.conn.scalar(f"SELECT COUNT(*) FROM {SCHEMA}.{table}", default=0)) for table in self.tracked_tables()}
